version: '3.4'
services:
    api1:
        image: dailycashflowcontrolapi
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
            
    worker:
        image: worker
        restart: on-failure
        depends_on:
            - api1
            - rabbitmq
        build:
            context: .
            dockerfile: Dockerfile2
    
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        labels:
          NAME: "rabbitmq"
        ports:
          - "4369:4369"
          - "5671:5671"
          - "5672:5672"
          - "25672:25672"
          - "15671:15671"
          - "15672:15672"
    
networks: 
    backend:
        driver: bridge