version: '3.4'
services:
    dailycashflowcontrolapi:
        image: dailycashflowcontrolapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        restart: always
        build:
            context: .
            dockerfile: DockerfileDailyCashFlowControl
        ports:
            - '5000:5000'
            
    consolidatedresultsapi:
        image: consolidatedresultsapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        restart: on-failure
        depends_on:
            - dailycashflowcontrolapi
            - rabbitmq
        build:
            context: .
            dockerfile: DockerfileConsolidatedResults
        ports:
            - '5001:5001'
            
    nextjs:
        depends_on:
            - consolidatedresultsapi
        ports:
          - 3000:3000
        build:
          context: web-app/daily-cash-flow-control-web
          dockerfile: Dockerfile
        environment:
          NODE_ENV: development
            
    
    
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        labels:
          NAME: "rabbitmq"
        ports:
          - "4369:4369"
          - "5671:5671"
          - "5672:5672"
          - "25672:25672"
          - "15671:15671"
          - "15672:15672"