version: '3.4'
services:
    dailycashflowcontrolapi:
        image: dailycashflowcontrolapi
        restart: always
        build:
            context: .
            dockerfile: DockerfileDailyCashFlowControl
        ports:
            - '5000:5000'
            
    consolidatedresultsapi:
        image: consolidatedresultsapi
        restart: always
        build:
            context: .
            dockerfile: DockerfileConsolidatedResults
        ports:
            - '5001:5001'
            
    worker:
        image: worker
        restart: on-failure
        depends_on:
            - dailycashflowcontrolapi
            - rabbitmq
        build:
            context: .
            dockerfile: DockerfileWorker
    
    rabbitmq: # login guest:guest
        image: rabbitmq:3-management
        hostname: "rabbitmq"
        labels:
          NAME: "rabbitmq"
        ports:
          - "4369:4369"
          - "5671:5671"
          - "5672:5672"
          - "25672:25672"
          - "15671:15671"
          - "15672:15672"
    
networks: 
    backend:
        driver: bridge